### ISSUE TITLE
SCTP AUTH may be disabled in kernel

### ISSUE THREAD

**Issue by ValeriyKr** [nplab/DTLS-Examples#15]
I've followed all the README steps, but got the next error:
```
$ LD_LIBRARY_PATH=/opt/openssl/lib ./dtls_sctp_echo 
139858668435264:error:20091002:BIO routines:BIO_new_dgram_sctp:system lib:crypto/bio/bss_dgram.c:844:Ensure SCTP AUTH chunks are enabled in kernel
```

As pointed here: [https://github.com/openssl/openssl/issues/8582#issuecomment-476554837](https://github.com/openssl/openssl/issues/8582#issuecomment-476554837), this message shows that SCTP AUTH chuncks are disabled in the kernel.

I suggest to add to README recommendation to check that `/proc/sys/net/sctp/auth_enable` contains `1`. Otherwise, to run
```
sysctl -w net.sctp.auth_enable=1
```
as root.

**Comment by ValeriyKr** [comment]
Forgot to mention, i'm using Debian 10.1, linux kernel 4.19.0, OpenSSL 1.1.1e-dev (branch `OpenSSL_1_1_1-stable` form github), if it matters.

**Comment by weinrank** [comment]
Hi Valeriy,

the setting you mentioned is already present in the README:

In addition to a loaded SCTP module, Linux requires SCTP AUTH support.
```
$ modprobe sctp
$ sysctl -w net.sctp.auth_enable=1
```

The only difference ist hat we don't explicitly advise to run this as root. 

Felix

**Comment by ValeriyKr** [comment]
Hello, Felix.

I'm very sorry for my carelessness. Didn't see the line after `modprobe`. Think, the issue can be closed.

**Comment by weinrank** [comment]
Okay! :)
